name: R-CMD-check

on:
  push:
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
      - name: Check
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          R CMD check args: --no-manual
        run: |
          remotes::install_github("r-lib/actions")
          rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "error", check_dir = "check")
